### ISSUE TITLE
can not run parallel protractor tests on Selenium Server

### ISSUE THREAD

**Issue by chisonne** [issacg/mocha-bamboo-reporter#12]
I am running protractor tests through Selenium Server on a number of browsers simultaneously.
The mocha bamboo reporter wirtes the results to mocha.json after each test. But when starting the next tests it removes that file. Which means only the results from the last test are being saved.

So I modified the reporter locally by reading the results, adding the new result and writing it back to the file.
This only works when running tests sequentially as 2 tests finishing at the same time would miss each other's results.

Is there any chance the bamboo reporter will be updated by supporting parallel runs?

**Comment by issacg** [comment]
Use ```--reporter-options output``` to write to different files?

**Comment by chisonne** [comment]
Thanks for your answer!
I didn't think it was possible to write output to multiple files with this option. But it works! :+1: 

Each tests writes its results to `TIMESTAMP-mocha.json` now. And the Bamboo parser is using the pattern: `*mocha.json`
